# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
- script: sudo dpkg -i packages-microsoft-prod.deb
- script: sudo apt-get install apt-transport-https
- script: sudo apt-get update
- script: sudo apt-get install dotnet-sdk-3.0.100-preview-010184
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
